### ISSUE TITLE
Why is an object created with Object.create(null) not considered to be a plain object?

### ISSUE THREAD

**Issue by OmarDarwish** [jonschlinkert/is-plain-object#12] opened 2018-02-23 19:27 UTC
For performance reasons, some applications choose to create objects without prototypes so that they can avoid the missing property chain lookup that is done on other objects.

I'm wondering why this project makes the distinction that an object created via `Object.create(null)` is considered not be a plain object. If anyone could clarify, I'd love to learn something! 😄

**Comment by jonschlinkert** [comment] 2018-02-24 09:43
I first want to say that I agree with your point, and I've thought about changing this to allow objects created the way you're describing, exactly for the reason you're giving. This [isn't the first time](https://github.com/jonschlinkert/is-plain-object/issues/11) I've had an issue about this or discussed it (and I'm not saying that to discourage the discussion, on the contrary, I'm mentioning it to let you know that I'm slowly rethinking my position).

> I'm wondering why this project makes the distinction that an object created via Object.create(null) is considered not be a plain object.

For this simple reason:

```js
const foo = Object.create({});
const bar = Object.create(null);
console.log(foo.constructor); //=> [Function: Object]
console.log(bar.constructor); //=> undefined
```

When you read other definitions, people have to give long and detailed explanations of what "plain object" means. Like [these answers](https://www.quora.com/What-is-a-plainObject-in-JavaScript). 

The definition here is much more clear, but I would consider updating this lib to allow the definition to be expanded to: "An object that was created by the `Object` constructor, or `Object.create(null)`". 

@doowb @stevenvachon, any thoughts?

**Comment by doowb** [comment] 2018-02-24 17:30
> The definition here is much more clear, but I would consider updating this lib to allow the definition to be expanded to: "An object that was created by the Object constructor, or Object.create(null)".

I agree that we can update this so that an object created with `Object.create(null)` is considered a plain object. `lodash` and `jQuery` both consider that to be the case and I think it makes sense since it creates the "plainest" object that can be created... it's literally just the `key: value` properties that are put on it.

**Comment by OmarDarwish** [comment] 2018-02-24 17:34
So it seems like you both are in support of expanding this project's definition of a plain object. Would this updated definition be the default going forward with an opt-out flag for old behavior, or would it be an opt-in flag?

**Comment by jonschlinkert** [comment] 2018-02-26 10:37
> it seems like you both are in support of expanding this project's definition of a plain object

Probably, but I need to think about it a little more. I was reminded by the readme that [isobject](https://github.com/jonschlinkert/isobject) was intended to be used for this use case. If we do make this change, I don't think we should take options, it should just do what's expected. If we think it's necessary to take options, then that probably means there is change it won't be doing what's expected..

**Comment by TrySound** [comment] 2019-04-28 13:41
@jonschlinkert Is this still a thing?

**Comment by TrySound** [comment] 2020-07-21 00:11
Fixed in v4
https://github.com/jonschlinkert/is-plain-object/releases/tag/v4.0.0

**Closed by TrySound** 2020-07-21 00:11 UTC
